# Generated by Django 3.2.3 on 2021-05-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_property', models.CharField(blank=True, choices=[('Квартира', 'Квартира'), ('Дом', 'Дом'), ('Участок', 'Участок'), ('Коммерческая недвижимость', 'Коммерческая недвижимость')], max_length=255, null=True, verbose_name='Ваши Объекты')),
                ('own', models.CharField(blank=True, choices=[('Собственность', 'Собственность'), ('Не оформлено', 'Не оформлено')], max_length=255, null=True, verbose_name='Собственность\\ не оформлено')),
                ('city', models.CharField(max_length=255, verbose_name='Город \\ район')),
                ('areas', models.CharField(blank=True, max_length=255, null=True, verbose_name='Площадь кв\\м, сотки')),
                ('floor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Этаж \\ этажность')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('number', models.CharField(max_length=255, verbose_name='Номер телефона')),
            ],
        ),
    ]
