# Generated by Django 3.2.3 on 2021-05-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postrentsale',
            options={'ordering': ['-id'], 'verbose_name': 'Тип недвижимости', 'verbose_name_plural': 'Тип недвижимости'},
        ),
        migrations.AddField(
            model_name='reviews',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
