# Generated by Django 3.2.3 on 2021-05-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postrentsale',
            options={'ordering': ['-id'], 'verbose_name': 'объект', 'verbose_name_plural': 'Все объекты'},
        ),
        migrations.AlterField(
            model_name='postrentsale',
            name='status',
            field=models.CharField(blank=True, choices=[('С ремонтом', 'С ремонтом'), ('Без ремонта', 'Без ремонта ')], max_length=255, null=True, verbose_name='Состояние'),
        ),
    ]
