# Generated by Django 3.2.3 on 2021-05-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nikname', models.CharField(max_length=255, verbose_name='Никнейм')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Фото')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/', verbose_name='Видео')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
        ),
    ]
